name: my-first-workflow
on:
  push:
    branches:
      - dev
      - 'feature-*'
      - main
  pull_request:
    branches:
        - main

env:
  ENV_TYPE: dev
  APP_USER: Thinknyx
  APP_PORT: 80
  
  
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step-2 Checkout
        uses: actions/checkout@v4

      - name: Step-3
        run: |
          echo $(pwd) >> myartifact.txt

      - name: Upload a single file
        uses: actions/upload-artifact@v4
        with:
          name: single_file
          path: ./myartifact.txt


  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v8
        with:
          name: single_file

      - name: Referring  Environment Variables
        run : |
            echo "Environment Type is $ENV_TYPE"
            echo "Application User is $APP_USER"
            echo "Application Port is $APP_PORT"
